version: '3'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    ports:
      - 3307:3306
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8081

#  nginx:
#    build: docker/nginx
#    ports:
#      - 8080:80
#    depends_on:
#      - php
#    volumes:
#      - ./:/var/www/symfony
#      - ./logs/nginx/:/var/log/nginx
#
#  php:
#    build: docker/php-fpm
#    ports:
#      - 9002:9000
#    volumes:
#      - ./:/var/www/symfony
#      - ./logs/symfony:/var/www/symfony/var/logs
#    depends_on:
#      - mysql
#      - redis
#      - rabbitmq
#
#  rabbitmq:
#    build: docker/rabbitmq
#    ports:
#      - 4369:4369
#      - 5672:5672
#      - 25672:25672
#      - 15672:15672
#
#  redis:
#    image: redis:5.0
#    ports:
#      - 6379:6379
#
#  frontend:
#    build: docker/frontend
#    volumes:
#      - ./:/var/www/html