version: '3'

services:
  nginx:
    build: docker/nginx
    ports:
      - 8080:80
    depends_on:
      - php
    volumes:
      - ./:/var/www/symfony
      - ./logs/nginx/:/var/log/nginx

  php:
    build: docker/php-fpm
    expose:
      - 9000
    volumes:
      - ./:/var/www/symfony
    depends_on:
      - mysql

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    expose:
      - 3306
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d

  frontend:
    build: docker/frontend
    volumes:
      - ./:/var/www/html